import { useState, useEffect } from "react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from "recharts";

// SVG Icons
const Icons = {
  BarChart: () => <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M5 9.2h3V19H5zM10.6 5h2.8v14h-2.8zm5.6 8H19v6h-2.8z" /></svg>,
  TrendingUp: () => <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M16 6l2.29 2.29-4.29 4.29-4-4L2 16.59 3.41 18 10 11.41l4 4 6.3-6.29L22 12v-6z" /></svg>,
  Info: () => <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z" /></svg>,
};

function Analytics() {
  const [period, setPeriod] = useState("daily");
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [hoveredTerm, setHoveredTerm] = useState(null);

  const tooltips = {
    usage: "Total electricity consumed from the grid during this period.",
    solar: "Energy generated by solar panels during peak hours.",
    cost: "Electricity charges based on consumption and rate per kWh.",
  };

  useEffect(() => {
    fetchAnalytics();
  }, [period]);

  async function fetchAnalytics() {
    setLoading(true);
    try {
      const res = await fetch(`${process.env.REACT_APP_API_URL}/analytics?period=${period}`);
      const json = await res.json();
      setData(Array.isArray(json.data) ? json.data : []);
    } catch (err) {
      console.error("Error fetching analytics:", err);
      setData([]);
    }
    setLoading(false);
  }

  const totalUsage = data.reduce((sum, d) => sum + (d.usage || 0), 0).toFixed(1);
  const totalSolar = data.reduce((sum, d) => sum + (d.solar || 0), 0).toFixed(1);
  const totalCost = data.reduce((sum, d) => sum + (d.cost || 0), 0).toFixed(0);
  const solarPercent = totalUsage > 0 ? ((totalSolar / totalUsage) * 100).toFixed(0) : 0;

  return (
    <div className="w-full bg-black overflow-hidden">
      {/* Background Effects */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-cyan-600/20 rounded-full blur-3xl animate-blob"></div>
        <div className="absolute top-1/4 right-0 w-96 h-96 bg-blue-600/20 rounded-full blur-3xl animate-blob animation-delay-2000"></div>
        <div className="absolute bottom-0 left-1/2 w-96 h-96 bg-emerald-600/20 rounded-full blur-3xl animate-blob animation-delay-4000"></div>
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.02)_1px,transparent_1px)] bg-[size:50px_50px]"></div>
      </div>

      <div className="relative z-10 p-6">
        <div className="max-w-7xl mx-auto">
          {/* Header */}
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-12 h-12 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-lg flex items-center justify-center">
                <Icons.BarChart />
              </div>
              <h1 className="text-5xl font-bold text-white">Energy Analytics</h1>
            </div>
            <p className="text-gray-400 text-lg">Historical energy consumption and solar generation insights</p>
          </div>

          {/* Period Filter */}
          <div className="flex gap-4 mb-10">
            {["daily", "weekly", "monthly"].map((p) => (
              <button
                key={p}
                onClick={() => setPeriod(p)}
                className={`px-8 py-3 rounded-lg font-semibold capitalize transition-all duration-300 ${
                  period === p
                    ? "bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/30 scale-105"
                    : "bg-white/5 border border-white/10 text-gray-300 hover:bg-white/10 hover:border-cyan-500/30"
                }`}
              >
                {p}
              </button>
            ))}
          </div>

          {/* Stats Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-10">
            <div className="group relative p-6 rounded-2xl border border-white/5 bg-gradient-to-br from-blue-500/10 to-cyan-500/5 backdrop-blur-sm hover:border-blue-500/30 transition-all duration-300">
              <div className="flex items-center justify-between mb-3">
                <p className="text-sm text-gray-400">Total Usage</p>
                <button
                  onMouseEnter={() => setHoveredTerm('usage')}
                  onMouseLeave={() => setHoveredTerm(null)}
                  className="relative p-1 text-gray-500 hover:text-blue-400"
                >
                  <Icons.Info />
                  {hoveredTerm === 'usage' && (
                    <div className="absolute right-0 top-8 w-48 bg-slate-900 border border-blue-500/30 rounded-lg p-3 text-xs text-gray-300 shadow-xl z-50">
                      {tooltips.usage}
                    </div>
                  )}
                </button>
              </div>
              <p className="text-4xl font-bold text-white">{totalUsage}</p>
              <p className="text-sm text-blue-300 mt-2">kWh</p>
            </div>

            <div className="group relative p-6 rounded-2xl border border-white/5 bg-gradient-to-br from-amber-500/10 to-orange-500/5 backdrop-blur-sm hover:border-amber-500/30 transition-all duration-300">
              <div className="flex items-center justify-between mb-3">
                <p className="text-sm text-gray-400">Solar Generated</p>
                <button
                  onMouseEnter={() => setHoveredTerm('solar')}
                  onMouseLeave={() => setHoveredTerm(null)}
                  className="relative p-1 text-gray-500 hover:text-amber-400"
                >
                  <Icons.Info />
                  {hoveredTerm === 'solar' && (
                    <div className="absolute right-0 top-8 w-48 bg-slate-900 border border-amber-500/30 rounded-lg p-3 text-xs text-gray-300 shadow-xl z-50">
                      {tooltips.solar}
                    </div>
                  )}
                </button>
              </div>
              <p className="text-4xl font-bold text-white">{totalSolar}</p>
              <p className="text-sm text-amber-300 mt-2">kWh</p>
            </div>

            <div className="group relative p-6 rounded-2xl border border-white/5 bg-gradient-to-br from-purple-500/10 to-pink-500/5 backdrop-blur-sm hover:border-purple-500/30 transition-all duration-300">
              <div className="flex items-center justify-between mb-3">
                <p className="text-sm text-gray-400">Total Cost</p>
                <button
                  onMouseEnter={() => setHoveredTerm('cost')}
                  onMouseLeave={() => setHoveredTerm(null)}
                  className="relative p-1 text-gray-500 hover:text-purple-400"
                >
                  <Icons.Info />
                  {hoveredTerm === 'cost' && (
                    <div className="absolute right-0 top-8 w-48 bg-slate-900 border border-purple-500/30 rounded-lg p-3 text-xs text-gray-300 shadow-xl z-50">
                      {tooltips.cost}
                    </div>
                  )}
                </button>
              </div>
              <p className="text-4xl font-bold text-white">₹{totalCost}</p>
              <p className="text-sm text-purple-300 mt-2">INR</p>
            </div>

            <div className="p-6 rounded-2xl border border-white/5 bg-gradient-to-br from-emerald-500/10 to-teal-500/5 backdrop-blur-sm hover:border-emerald-500/30 transition-all duration-300">
              <p className="text-sm text-gray-400 mb-3">Solar Coverage</p>
              <p className="text-4xl font-bold text-white">{solarPercent}%</p>
              <p className="text-sm text-emerald-300 mt-2">of demand met</p>
            </div>
          </div>

          {/* Main Chart */}
          <div className="p-8 rounded-3xl border border-white/5 bg-white/[0.02] backdrop-blur-sm hover:border-white/10 transition-all duration-300 mb-8 shadow-2xl">
            <div className="flex items-center justify-between mb-8">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-lg flex items-center justify-center">
                  <Icons.TrendingUp />
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-white">Energy Usage vs Solar Generation</h3>
                  <p className="text-gray-400 mt-1 capitalize">{period} energy overview</p>
                </div>
              </div>
              <div className="px-4 py-2 rounded-full bg-cyan-500/20 border border-cyan-400/20 text-cyan-300 text-sm font-semibold">
                Live Analytics
              </div>
            </div>

            {loading ? (
              <div className="h-[350px] flex items-center justify-center text-gray-400">
                <div className="text-center space-y-3">
                  <div className="w-10 h-10 border-2 border-cyan-500/30 border-t-cyan-500 rounded-full animate-spin mx-auto"></div>
                  <p>Loading analytics...</p>
                </div>
              </div>
            ) : data.length > 0 ? (
              <ResponsiveContainer width="100%" height={350}>
                <BarChart data={data} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                  <XAxis dataKey="label" tick={{ fill: "#cbd5e1", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#cbd5e1", fontSize: 12 }} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "#0f172a",
                      border: "1px solid #334155",
                      borderRadius: "12px",
                      color: "#fff"
                    }}
                  />
                  <Legend />
                  <Bar dataKey="usage" name="Usage (kWh)" fill="#06b6d4" radius={[8, 8, 0, 0]} />
                  <Bar dataKey="solar" name="Solar (kWh)" fill="#fbbf24" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-[350px] flex items-center justify-center text-gray-400">
                No data available
              </div>
            )}
          </div>

          {/* Cost Chart */}
          <div className="p-8 rounded-3xl border border-white/5 bg-white/[0.02] backdrop-blur-sm hover:border-white/10 transition-all duration-300 shadow-2xl">
            <div className="mb-8">
              <h3 className="text-2xl font-bold text-white">Monthly Cost Trend</h3>
              <p className="text-gray-400 mt-1">Energy spending insights and projections</p>
            </div>

            {loading ? (
              <div className="h-[250px] flex items-center justify-center text-gray-400">
                <div className="text-center space-y-3">
                  <div className="w-10 h-10 border-2 border-cyan-500/30 border-t-cyan-500 rounded-full animate-spin mx-auto"></div>
                  <p>Loading cost data...</p>
                </div>
              </div>
            ) : data.length > 0 ? (
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={data} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                  <XAxis dataKey="label" tick={{ fill: "#cbd5e1", fontSize: 12 }} />
                  <YAxis tick={{ fill: "#cbd5e1", fontSize: 12 }} />
                  <Tooltip
                    formatter={(value) => [`₹${value}`, "Cost"]}
                    contentStyle={{
                      backgroundColor: "#0f172a",
                      border: "1px solid #334155",
                      borderRadius: "12px",
                      color: "#fff"
                    }}
                  />
                  <Bar dataKey="cost" name="Cost (₹)" fill="#f97316" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-[250px] flex items-center justify-center text-gray-400">
                No data available
              </div>
            )}
          </div>
        </div>
      </div>

      <style>{`
        @keyframes blob {
          0%, 100% { transform: translate(0, 0) scale(1); }
          33% { transform: translate(30px, -50px) scale(1.1); }
          66% { transform: translate(-20px, 20px) scale(0.9); }
        }
        .animate-blob { animation: blob 7s infinite; }
        .animation-delay-2000 { animation-delay: 2s; }
        .animation-delay-4000 { animation-delay: 4s; }
      `}</style>
    </div>
  );
}

export default Analytics;